### ISSUE TITLE
Structures spawning without floors or only 1 block floors

### ISSUE THREAD

**Issue by VallenFrostweaver** [superlord9362/GoblinsAndDungeons#12]
Minecraft 1.18.1
Forge 39.0.75
Goblins & Dungeons 1.0.5

Suggestion: In your structure building I would recommend adding in a floor as well as several layers of dirt, stone, etc. surrounding the structure so that when a structure spawns on a slope or ledge it then can support the mobs (a floor - see image below for issue) or to avoid the weird flat floaty structures. Essentially, make each a small floating island of rounded materials (dirt, stone, etc) below the structures so they will look more natural.

No floor issue:
![image](https://user-images.githubusercontent.com/13642054/156770538-bbb0a4e6-ed4d-4d96-9902-9a4cf8ca1051.png)

Flat floor on slope issue:
![image](https://user-images.githubusercontent.com/13642054/156771305-5cc7804e-469e-4041-b818-c614687c4a3e.png)

**Comment by superlord9362** [comment]
Fixed for 1.0.6
