### ISSUE TITLE
Ogre barely moves and puts arms inside and behind itself

### ISSUE THREAD

**Issue by VallenFrostweaver** [superlord9362/GoblinsAndDungeons#13]
Minecraft 1.18.1
Forge 39.0.75
Goblins & Dungeons 1.0.5

I stood there for almost 5 minutes before it could reach me then it started doing this. See image:
![image](https://user-images.githubusercontent.com/13642054/156775343-e0fbb1c7-524c-4b25-be56-cec280d2fa1c.png)

**Comment by superlord9362** [comment]
Fixed for 1.0.6
