### ISSUE TITLE
Gobbers suffocate due to large hitbox

### ISSUE THREAD

**Issue by VallenFrostweaver** [superlord9362/GoblinsAndDungeons#14]
Minecraft 1.18.1
Forge 39.0.75
Goblins & Dungeons 1.0.5

Gobbers will occasionally suffocate themselves. Their hitbox is slightly wider than a 1 wide x2 tall block opening and when traveling through these openings will start to take suffocation damage.
![image](https://user-images.githubusercontent.com/13642054/156796308-f0f16f46-8342-4f40-aef6-bab1d56b2897.png)

**Comment by superlord9362** [comment]
Fixed for 1.0.6
