### ISSUE TITLE
Crash with quark

### ISSUE THREAD

**Issue by zEpiixz** [superlord9362/GoblinsAndDungeons#2]
https://pastebin.com/5qFQ7034

**Comment by superlord9362** [comment]
Could you give me more information on what was happening at the time of the crash?

**Comment by zEpiixz** [comment]
I died from a goblin a totem of holding spawned, then i respawned and it insta crashed. 
I think it was an goblin archer killing me if i remember correctly.

**Comment by superlord9362** [comment]
Should be fixed for 1.0.4
