### ISSUE TITLE
game crashes when putting ring in anvil (1.18.2)

### ISSUE THREAD

**Issue by MoonMoonShark** [superlord9362/GoblinsAndDungeons#32]
Minecraft: 1.18.2
Forge: 40.1.84
Goblins & Dungeons: Goblins_Dungeons_1.0.8.jar

crash log: 
[crash-2022-11-13_06.28.50-client.txt](https://github.com/superlord9362/GoblinsAndDungeons/files/9997070/crash-2022-11-13_06.28.50-client.txt)

**Comment by SettingDust** [comment]
Huh. Will you publish it? @superlord9362
