### ISSUE TITLE
Goblin 3d Model Ressource pack

### ISSUE THREAD

**Issue by InkyBone** [superlord9362/GoblinsAndDungeons#33]
I am trying to make gobblin and dungeons compatible with epic fight. But for this i would need to make a ressource pack with the 3D models of the goblins. How coudl i acess them ?

**Comment by superlord9362** [comment]
This isn't an issue, and would have been better communicated on the discord or curseforge. You can load them through Tabula by importing them in the same way you can import vanilla models, so long as the mod is installed.
