### ISSUE TITLE
Client crash near goblin king castle

### ISSUE THREAD

**Issue by IsPherz** [superlord9362/GoblinsAndDungeons#4]
Hey so I was wandering the world and found like a castle of goblins and got like a boss goblin bar or something on top of my secreen some seconds a fter I freeze and my game crashes, currently if I try  to rejoin(Im playing on a server I just get to crash again) 
this is my crash report:https://pastebin.com/k0C03xab
Here  is  a video re creating the issue
https://streamable.com/5m5mzz
also seems like this causes some tick lag on the  server when I get the crash
​​‍‍​​​‍​​‍‍​‍‍​​​‍‍​​‍‍​​‍‍‍​​‍​​‍‍​‍​​​​‍‍​‍​‍​​‍‍​‍​‍​​‍‍​​​‍​​‍‍​​‍​​​‍‍​‍​‍​​‍‍​​​​​​‍‍​​​​​​‍‍​​​​13.12 23:12:05 [Server] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 8917ms or 178 ticks behind
let me know if you need anything  else

**Comment by superlord9362** [comment]
Fixed for next update

**Comment by IsPherz** [comment]
Hey thank you I was uploading a video to give more context, can you tell me what makes the client to crash? o any info about why  it happens?

**Comment by superlord9362** [comment]
Was a leftover line that was causing issues with some animation mods you had, it seems.
