### ISSUE TITLE
Error on console

### ISSUE THREAD

**Issue by Congraz8961** [superlord9362/GoblinsAndDungeons#6]
Every time I restart the server, these 4 messages appear on the console. I do not notice any issues with it in the game, so it runs fine. But have no idea why it shows up on the console when it runs fine on the server. Can it cause problems in the future? 🤞 

![image](https://user-images.githubusercontent.com/56209437/147153402-fd7fa035-9314-48d1-a961-5201cb6879c6.png)

**Comment by superlord9362** [comment]
Nope, this isn't an issue. Game should run perfectly fine. Just means that structure gen will be vanilla based instead of Terraforged base.
